export const SELECT_DEVICE_QUERY_LIST = 'device_query/SELECT_DEVICE_QUERY_LIST';
export const GET_ALL_DEVICE_QUERY_INFO = 'device_query/GET_ALL_DEVICE_QUERY_INFO';
export const GET_DEVICE_DETAILS_INFO = 'device_query/GET_DEVICE_DETAILS_INFO'
export const HANDLE_DEVICE_QUERY_NEW_BUILD = 'device_query/HANDLE_DEVICE_QUERY_NEW_BUILD'
export const HANDLE_DEVICE_QUERY_SUMBIT = 'device_query/HANDLE_DEVICE_QUERY_SUMBIT'
export const HANDLE_DEVICE_QUERY_CANCEL = 'device_query/HANDLE_DEVICE_QUERY_CANCEL'
export const HANDLE_CONSOLE_CLICK = 'device_query/HANDLE_CONSOLE_CLICK'
export const HANDLE_CONSOLE_CANCEL = 'device_query/HANDLE_CONSOLE_CANCEL'
export const GET_CONSOLE_SUBMIT_INFO = 'device_query/GET_CONSOLE_SUBMIT_INFO'
export const SETUP_CONSOLE_SUBMIT_STATUS = 'device_query/SETUP_CONSOLE_SUBMIT_STATUS'
export const HANDLE_PROTOCOL_CHANGE = 'device_query/HANDLE_PROTOCOL_CHANGE'
export const GET_DEVICE_PORT_MACS = 'device_query/GET_DEVICE_PORT_MACS'
export const GET_DEVICE_PORT_ARP = 'device_query/GET_DEVICE_PORT_ARP'
export const HANDLE_DEVICE_QUERY_SEARCH = 'device_query/HANDLE_DEVICE_QUERY_SEARCH'
export const HANDLE_MODEL_CHANGE = 'device_query/HANDLE_MODEL_CHANGE'
export const HANDLE_AUTO_DEVICE_QUERY_SWITCH = 'device_query/HANDLE_AUTO_DEVICE_QUERY_SWITCH'
export const HANDLE_ADD_FIELD = 'device_query/HANDLE_ADD_FIELD'
export const HANDLE_DELETE_MODEL = 'device_query/HANDLE_DELETE_MODEL'
export const HANDLE_EDIT_DEVICE_QUERY = 'device_query/HANDLE_EDIT_DEVICE_QUERY'
export const HANDLE_NETWORK_SET = 'HANDLE_NETWORK_SET'
export const HANDLE_NETWORK_SET_LOADING = 'HANDLE_NETWORK_SET_LOADING'
export const NETWORK_SET_CANCEL = 'NETWORK_SET_CANCEL'
export const NETWORK_SET_SUBMIT = 'NETWORK_SET_SUBMIT'




// handleModalBtnCancelClick

