# Generated by Django 2.0.6 on 2020-09-09 11:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkgroup',
            options={'verbose_name': '网络分组信息', 'verbose_name_plural': '网络分组信息'},
        ),
        migrations.AlterField(
            model_name='networkgroup',
            name='name',
            field=models.TextField(default='', unique=True, verbose_name='分组名称'),
        ),
        migrations.AlterModelTable(
            name='networkgroup',
            table='network_group',
        ),
    ]
