# Generated by Django 2.0.6 on 2020-09-09 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0002_auto_20200909_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkgroup',
            name='child',
            field=models.TextField(default='', verbose_name='子分组'),
        ),
    ]
