# Generated by Django 2.0.6 on 2020-09-11 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0003_networkgroup_child'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkgroup',
            name='child',
        ),
        migrations.RemoveField(
            model_name='networkgroup',
            name='parent',
        ),
    ]
