# Generated by Django 2.0.6 on 2020-09-17 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group_manage', '0004_auto_20200911_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkgroup',
            name='networks',
            field=models.TextField(default='[]', verbose_name='网络'),
        ),
    ]
