export const SELECT_DEVICE_QUERY_LIST = 'device_query/SELECT_DEVICE_QUERY_LIST';
export const GET_ALL_DEVICE_QUERY_INFO = 'device_query/GET_ALL_DEVICE_QUERY_INFO';
export const GET_DEVICE_DETAILS_INFO = 'device_query/GET_DEVICE_DETAILS_INFO'
export const HANDLE_DEVICE_QUERY_NEW_BUILD = 'device_query/HANDLE_DEVICE_QUERY_NEW_BUILD'
export const HANDLE_DEVICE_QUERY_SUMBIT = 'device_query/HANDLE_DEVICE_QUERY_SUMBIT'
export const HANDLE_DEVICE_QUERY_CANCEL = 'device_query/HANDLE_DEVICE_QUERY_CANCEL'
export const HANDLE_CONSOLE_CLICK = 'device_query/HANDLE_CONSOLE_CLICK'
export const HANDLE_CONSOLE_CANCEL = 'device_query/HANDLE_CONSOLE_CANCEL'
export const GET_CONSOLE_SUBMIT_INFO = 'device_query/GET_CONSOLE_SUBMIT_INFO'
export const SETUP_CONSOLE_SUBMIT_STATUS = 'device_query/SETUP_CONSOLE_SUBMIT_STATUS'
export const HANDLEPROTOCOLCHANGE = 'device_query/HANDLEPROTOCOLCHANGE'
export const GET_DEVICE_PORT_MACS = 'device_query/GET_DEVICE_PORT_MACS'
export const GET_DEVICE_PORT_ARP = 'device_query/GET_DEVICE_PORT_ARP'



// handleModalBtnCancelClick

