# Generated by Django 2.0.6 on 2020-09-17 11:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Networks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField(unique=True, verbose_name='网络')),
                ('ip_used', models.IntegerField(default=0, verbose_name='被使用IP地址数量')),
                ('ip_total', models.IntegerField(default=0, verbose_name='总的IP地址数量')),
                ('query_time', models.DateTimeField(default=datetime.datetime(2020, 9, 17, 19, 51, 43, 527181), verbose_name='最新探测时间')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2020, 9, 17, 19, 51, 43, 527210), verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网络信息',
                'verbose_name_plural': '网络信息',
                'db_table': 'networks',
            },
        ),
    ]
