# Generated by Django 2.0.6 on 2020-09-17 12:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks_manage', '0002_auto_20200917_1951'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 33, 22, 286938), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='networks',
            name='query_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 33, 22, 286909), verbose_name='最新探测时间'),
        ),
    ]
