# Generated by Django 2.0.6 on 2020-09-17 12:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks_manage', '0004_auto_20200917_2046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 47, 50, 738326), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='networks',
            name='query_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 20, 47, 50, 738298), verbose_name='最新探测时间'),
        ),
    ]
