# Generated by Django 2.0.6 on 2020-09-17 14:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks_manage', '0005_auto_20200917_2047'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 22, 43, 43, 19181), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='networks',
            name='query_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 9, 17, 22, 43, 43, 19154), verbose_name='最新探测时间'),
        ),
    ]
