# Generated by Django 2.0.6 on 2020-10-08 14:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks_manage', '0014_auto_20201007_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 22, 34, 51, 820106), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='networks',
            name='query_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 22, 34, 51, 820078), verbose_name='最新探测时间'),
        ),
    ]
