# Generated by Django 2.0.6 on 2020-10-08 15:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('networks_manage', '0016_auto_20201008_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networks',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 23, 0, 5, 754832), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='networks',
            name='query_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 10, 8, 23, 0, 5, 754805), verbose_name='最新探测时间'),
        ),
    ]
