export const HANDLE_BUILD_NETWORKS = 'HANDLE_BUILD_NETWORKS'
export const HANDLE_BUILD_NETWORKS_CANCEL = "HANDLE_BUILD_NETWORKS_CANCEL"
export const GET_ALL_NETWORK = 'GET_ALL_NETWORK'
export const NETWORK_SELECTED = 'NETWORK_SELECTED'
export const DETELE_NETWORK = 'DETELE_NETWORK'
export const DETELE_NETWORK_CANCEL = 'DETELE_NETWORK_CANCEL'
export const NETWORK_EXPORT = 'NETWORK_EXPORT'
export const NETWORK_EXPORT_CANCEL = 'NETWORK_EXPORT_CANCEL'
export const NETWORK_IMPORT = 'NETWORK_IMPORT'
export const NETWORK_IMPORT_CANCEL = 'NETWORK_IMPORT_CANCEL'
export const HANDLE_CSV_DATA = 'HANDLE_CSV_DATA'
export const HANDLE_CSV_DATA_START = 'HANDLE_CSV_DATA_START'
export const GET_IP_DETAIL_INFO = 'GET_IP_DETAIL_INFO'
export const IP_DETAILS_SELECTED = 'IP_DETAILS_SELECTED'
export const EDIT_IP_DETAIL = 'EDIT_IP_DETAIL'
export const EDIT_IP_DETAIL_CANCEL = 'EDIT_IP_DETAIL_CANCEL'
export const FRESH_IP_DETAIL = 'FRESH_IP_DETAIL'
export const RESOLVE_IP_DETAIL_CONFLICT = 'RESOLVE_IP_DETAIL_CONFLICT'
export const RESOLVE_IP_CONFLICT_CANCEL = 'RESOLVE_IP_CONFLICT_CANCEL'
export const CONVERT_TO_MANUAL = 'CONVERT_TO_MANUAL'
export const CONVERT_IP_MANUAL_CANCEL = 'CONVERT_IP_MANUAL_CANCEL'





