export const HANDLE_BUILD_NETWORKS = 'HANDLE_BUILD_NETWORKS'
export const HANDLE_BUILD_NETWORKS_CANCEL = "HANDLE_BUILD_NETWORKS_CANCEL"
export const GET_ALL_NETWORK = 'GET_ALL_NETWORK'
export const NETWORK_SELECTED = 'NETWORK_SELECTED'
export const DETELE_NETWORK = 'DETELE_NETWORK'
export const DETELE_NETWORK_CANCEL = 'DETELE_NETWORK_CANCEL'
export const NETWORK_EXPORT = 'NETWORK_EXPORT'
export const NETWORK_EXPORT_CANCEL = 'NETWORK_EXPORT_CANCEL'
export const NETWORK_IMPORT = 'NETWORK_IMPORT'
export const NETWORK_IMPORT_CANCEL = 'NETWORK_IMPORT_CANCEL'
export const HANDLE_CSV_DATA = 'HANDLE_CSV_DATA'
export const HANDLE_CSV_DATA_START = 'HANDLE_CSV_DATA_START'
export const GET_IP_DETAIL_INFO = 'GET_IP_DETAIL_INFO'




