# Generated by Django 2.0.6 on 2020-08-18 04:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydevice',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 12, 26, 31, 174093), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='querydevice',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 12, 26, 31, 174176), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='querydevice',
            name='query_status',
            field=models.SmallIntegerField(choices=[(0, '未启动'), (1, '等待中'), (2, '探测完成'), (3, '路由不可达'), (4, '未知错误'), (5, '端口未开放'), (6, '探测中...')], default=0, verbose_name='探测状态'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 12, 26, 31, 177931), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 12, 26, 31, 178013), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 12, 26, 31, 176196), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 18, 12, 26, 31, 176290), verbose_name='修改时间'),
        ),
    ]
