# Generated by Django 2.0.6 on 2020-08-20 14:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_query', '0003_auto_20200820_2217'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydevice',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 19, 28, 385414), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='querydevice',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 19, 28, 385500), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 19, 28, 388470), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 19, 28, 388537), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 19, 28, 387067), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 19, 28, 387123), verbose_name='修改时间'),
        ),
    ]
