# Generated by Django 2.0.6 on 2020-08-20 14:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_query', '0004_auto_20200820_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydevice',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 21, 49, 936039), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='querydevice',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 21, 49, 936177), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 21, 49, 942346), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 21, 49, 942465), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 21, 49, 939510), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 21, 49, 939679), verbose_name='修改时间'),
        ),
    ]
