# Generated by Django 2.0.6 on 2020-08-20 14:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('device_query', '0005_auto_20200820_2221'),
    ]

    operations = [
        migrations.AlterField(
            model_name='querydevice',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 22, 35, 52796), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='querydevice',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 22, 35, 52956), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 22, 35, 57469), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryiproutetable',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 22, 35, 57667), verbose_name='修改时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='created_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 22, 35, 55310), verbose_name='创建时间'),
        ),
        migrations.AlterField(
            model_name='snmpqueryresult',
            name='last_mod_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 8, 20, 22, 22, 35, 55419), verbose_name='修改时间'),
        ),
    ]
