# Generated by Django 2.0.6 on 2020-08-30 14:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkQueryDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField(verbose_name='探测网络')),
                ('ip', models.GenericIPAddressField(unique=True, verbose_name='ip地址')),
                ('scan_mac', models.CharField(max_length=30, verbose_name='MAC地址')),
                ('scan_mac_product', models.CharField(max_length=60, verbose_name='MAC地址')),
                ('tcp_port_list', models.TextField(default='', verbose_name='TCP端口探测数据')),
                ('udp_port_list', models.TextField(default='', verbose_name='UDP端口探测数据')),
                ('hostname', models.CharField(max_length=60, verbose_name='MAC地址')),
                ('ip_status', models.SmallIntegerField(choices=[(0, '离线'), (1, '在线')], default=0, verbose_name='IP地址状态')),
                ('ip_type', models.SmallIntegerField(choices=[(0, '未管理'), (1, '手动地址'), (2, '未使用')], default=0, verbose_name='IP地址类型')),
                ('query_time', models.DateTimeField(default=datetime.datetime(2020, 8, 30, 22, 5, 35, 566614), verbose_name='最新探测时间')),
            ],
            options={
                'verbose_name': '网络探测IP信息',
                'verbose_name_plural': '网络探测IP信息',
                'db_table': 'network_query_result',
            },
        ),
        migrations.CreateModel(
            name='NetworkQueryList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('network', models.GenericIPAddressField(unique=True, verbose_name='探测网络')),
                ('tcp_query_ports', models.TextField(default='', verbose_name='TCP探测端口')),
                ('udp_query_ports', models.TextField(default='', verbose_name='UDP探测端口')),
                ('online_ip_num', models.IntegerField(default=0, verbose_name='在线地址数量')),
                ('auto_enable', models.BooleanField(default=False, verbose_name='定时任务开关')),
                ('query_status', models.SmallIntegerField(choices=[(0, '未启动'), (1, '等待中'), (2, '探测完成'), (3, '未知错误'), (4, '探测中...')], default=0, verbose_name='探测状态')),
                ('crontab_task', models.TextField(default='', verbose_name='定时任务时间')),
                ('query_time', models.DateTimeField(default=datetime.datetime(2020, 8, 30, 22, 5, 35, 565850), verbose_name='最新探测时间')),
                ('created_time', models.DateTimeField(default=datetime.datetime(2020, 8, 30, 22, 5, 35, 565877), verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '网络探测信息',
                'verbose_name_plural': '网络探测信息',
                'db_table': 'network_query_task',
            },
        ),
    ]
